apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: data-platform-postgres
  namespace: database

spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:18.4

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

    nodeSelector:
      workload: database

  storage:
    size: 10Gi

  postgresql:
    parameters:
      wal_level: logical
      max_replication_slots: "10"
      max_wal_senders: "10"
